[config]
set_wallpaper = false

[templates.rofi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.cache/matugen/colors.rasi'

[templates.hypr]
input_path = '~/.config/matugen/templates/theme.conf'
output_path = '~/.cache/matugen/theme.conf'

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.cache/matugen/gtk.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
